/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Document
         * @description One document with its markdown, as text.
         */
        get: operations["read_document_documents__document_id__get"];
        /**
         * Revise Document
         * @description Replace the content of a document with a newer version of the same file.
         *
         *     The uploaded name must match the stored one: a document is known to its
         *     readers by its name, so overwriting `runbook.md` with something else under
         *     that name is refused rather than silently accepted.
         */
        put: operations["revise_document_documents__document_id__put"];
        post?: never;
        /** Discard Document */
        delete: operations["discard_document_documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/elements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Elements
         * @description Browse the catalogue, narrowed by type, by layer or by a name fragment.
         */
        get: operations["list_elements_elements_get"];
        put?: never;
        /**
         * Create Element
         * @description Add an element to the catalogue.
         */
        post: operations["create_element_elements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/elements/{element_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Element */
        get: operations["read_element_elements__element_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Element
         * @description Remove an element and every relationship attached to it.
         */
        delete: operations["delete_element_elements__element_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Element
         * @description Change what an element says. Its type is fixed once created.
         */
        patch: operations["update_element_elements__element_id__patch"];
        trace?: never;
    };
    "/elements/{element_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Element Documents
         * @description What is attached to an element: the names and the sizes, not the text.
         *
         *     A 404 rather than an empty list when the element is unknown — an empty list
         *     is the answer to a different question.
         */
        get: operations["list_element_documents_elements__element_id__documents_get"];
        put?: never;
        /**
         * Attach Document
         * @description Attach a markdown file to an element.
         *
         *     The element must already exist, and it may hold only one document under a
         *     given file name — uploading the same name twice is a 409, and revising it
         *     is `PUT /documents/{document_id}`.
         */
        post: operations["attach_document_elements__element_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/elements/{element_id}/impact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Impact
         * @description What depends on this element, transitively.
         *
         *     Each hop is walked in the direction dependency actually runs, which is not
         *     always the direction the arrow is drawn: a service serves a process, but a
         *     whole is composed *of* its parts.
         */
        get: operations["read_impact_elements__element_id__impact_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/elements/{element_id}/neighbourhood": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Neighbourhood
         * @description The sub-graph around an element, following links in either direction.
         */
        get: operations["read_neighbourhood_elements__element_id__neighbourhood_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/elements/{element_id}/relationships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Element Relations
         * @description Every link attached to one element, with the elements at both ends.
         *
         *     `GET /relationships?element_id=` answers with the links alone, which is
         *     enough to count them but not to display one: a link stores the *types* of
         *     its endpoints, never their names. This returns the sub-graph instead, so a
         *     client renders "Invoice API serves Order to cash" from one response.
         */
        get: operations["read_element_relations_elements__element_id__relationships_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metamodel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Metamodel
         * @description Every element type, relationship type and layer ArchiMate 3.2 defines.
         */
        get: operations["read_metamodel_metamodel_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metamodel/matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Relationship Matrix
         * @description One row of the metamodel matrix: what `source` may point at, and how.
         *
         *     Appendix B publishes the whole 61x61 grid; a row is what a screen shows at
         *     a time, and asking for one keeps this a lookup instead of a 3721-cell
         *     payload. The cells are computed here, never stored, so they cannot drift
         *     from the rules the API rejects a link with.
         */
        get: operations["read_relationship_matrix_metamodel_matrix_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metamodel/relationships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Permitted Relationships
         * @description Which relationships may run between two element types, strongest first.
         */
        get: operations["read_permitted_relationships_metamodel_relationships_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/relationships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Relationships
         * @description List links, optionally only those touching one element.
         */
        get: operations["list_relationships_relationships_get"];
        put?: never;
        /**
         * Create Relationship
         * @description Link two elements, if ArchiMate allows that link between their types.
         */
        post: operations["create_relationship_relationships_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/relationships/{relationship_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Relationship */
        delete: operations["delete_relationship_relationships__relationship_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccessType
         * @description How an `ACCESS` relationship touches the passive element it points at.
         * @enum {string}
         */
        AccessType: "access" | "read" | "write" | "read_write";
        /**
         * Aspect
         * @description The aspect an element belongs to — the column of the ArchiMate framework.
         * @enum {string}
         */
        Aspect: "active_structure" | "behavior" | "passive_structure" | "motivation" | "composite" | "connector";
        /** Body_attach_document_elements__element_id__documents_post */
        Body_attach_document_elements__element_id__documents_post: {
            /**
             * File
             * @description A UTF-8 markdown file, at most 1 MB.
             */
            file: string;
        };
        /** Body_revise_document_documents__document_id__put */
        Body_revise_document_documents__document_id__put: {
            /**
             * File
             * @description A UTF-8 markdown file, at most 1 MB.
             */
            file: string;
        };
        /**
         * DocumentRead
         * @description One attached markdown file, content included — the whole document.
         *
         *     Not a subclass of the summary above: it would inherit an `of` that builds
         *     it from a `DocumentSummary`, which has no content to give it.
         */
        DocumentRead: {
            /**
             * Byte Size
             * @description Size of the stored markdown, in bytes.
             */
            byte_size: number;
            /**
             * Content
             * @description The markdown itself, as text.
             */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Element Id
             * Format: uuid
             */
            element_id: string;
            /** Filename */
            filename: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * DocumentSummaryRead
         * @description One attached markdown file, as a listing shows it — without its content.
         *
         *     The content is deliberately absent: a listing exists to name the files, and
         *     a client that received ten bodies to draw ten names would download
         *     megabytes to render a list. `GET /documents/{id}` is the read that carries
         *     the text.
         */
        DocumentSummaryRead: {
            /**
             * Byte Size
             * @description Size of the stored markdown, in bytes.
             */
            byte_size: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Element Id
             * Format: uuid
             */
            element_id: string;
            /** Filename */
            filename: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ElementCreate
         * @description A new architecture element.
         */
        ElementCreate: {
            /**
             * Description
             * @default
             */
            description?: string;
            /**
             * Documentation
             * @default
             */
            documentation?: string;
            element_type: components["schemas"]["ElementType"];
            /** Name */
            name: string;
            /**
             * Properties
             * @description Free-form attributes, e.g. owner or criticality.
             */
            properties?: {
                [key: string]: string;
            };
        };
        /**
         * ElementPage
         * @description One page of the catalogue, with the total so a client can paginate.
         */
        ElementPage: {
            /** Items */
            items: components["schemas"]["ElementRead"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * ElementRead
         * @description An element as the API exposes it, layer and aspect resolved for the caller.
         */
        ElementRead: {
            aspect: components["schemas"]["Aspect"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string;
            /** Documentation */
            documentation: string;
            element_type: components["schemas"]["ElementType"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            layer: components["schemas"]["Layer"];
            /** Name */
            name: string;
            /** Properties */
            properties: {
                [key: string]: string;
            };
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ElementType
         * @description Every element type ArchiMate 3.2 defines.
         *
         *     The member value is the wire and storage form: it appears in the OpenAPI
         *     schema and in the graph, so renaming one is a breaking change.
         * @enum {string}
         */
        ElementType: "stakeholder" | "driver" | "assessment" | "goal" | "outcome" | "principle" | "requirement" | "constraint" | "meaning" | "value" | "resource" | "capability" | "course_of_action" | "value_stream" | "business_actor" | "business_role" | "business_collaboration" | "business_interface" | "business_process" | "business_function" | "business_interaction" | "business_event" | "business_service" | "business_object" | "contract" | "representation" | "product" | "application_component" | "application_collaboration" | "application_interface" | "application_function" | "application_interaction" | "application_process" | "application_event" | "application_service" | "data_object" | "node" | "device" | "system_software" | "technology_collaboration" | "technology_interface" | "path" | "communication_network" | "technology_function" | "technology_process" | "technology_interaction" | "technology_event" | "technology_service" | "artifact" | "equipment" | "facility" | "distribution_network" | "material" | "work_package" | "deliverable" | "implementation_event" | "plateau" | "gap" | "location" | "grouping" | "junction";
        /**
         * ElementTypeRead
         * @description One entry of the metamodel catalogue, for building a palette in the SPA.
         */
        ElementTypeRead: {
            aspect: components["schemas"]["Aspect"];
            /** Label */
            label: string;
            layer: components["schemas"]["Layer"];
            value: components["schemas"]["ElementType"];
        };
        /**
         * ElementUpdate
         * @description A partial update. An omitted field keeps its stored value.
         *
         *     `element_type` is absent on purpose: changing it could invalidate
         *     relationships that already exist, which is a migration and not an edit.
         */
        ElementUpdate: {
            /** Description */
            description?: string | null;
            /** Documentation */
            documentation?: string | null;
            /** Name */
            name?: string | null;
            /** Properties */
            properties?: {
                [key: string]: string;
            } | null;
        };
        /**
         * ErrorResponse
         * @description The single error envelope every failing endpoint returns.
         */
        ErrorResponse: {
            /**
             * Detail
             * @description Human-readable message, safe to display.
             */
            detail: string;
            /**
             * Error
             * @description Stable machine-readable code.
             */
            error: string;
        };
        /**
         * GraphRead
         * @description A sub-graph: the nodes and the edges between them, ready to be drawn.
         */
        GraphRead: {
            /** Elements */
            elements: components["schemas"]["ElementRead"][];
            /** Relationships */
            relationships: components["schemas"]["RelationshipRead"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Declared so no internal field can leak into the response.
         */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /**
         * Layer
         * @description The layers of ArchiMate 3.2, plus the cross-layer `OTHER` grouping.
         * @enum {string}
         */
        Layer: "motivation" | "strategy" | "business" | "application" | "technology" | "physical" | "implementation_migration" | "other";
        /**
         * MetamodelRead
         * @description Everything a client needs to render and validate the ArchiMate palette.
         */
        MetamodelRead: {
            /** Element Types */
            element_types: components["schemas"]["ElementTypeRead"][];
            /** Layers */
            layers: components["schemas"]["Layer"][];
            /** Relationship Types */
            relationship_types: components["schemas"]["RelationshipTypeRead"][];
        };
        /**
         * RelationshipCategory
         * @description The four families the specification groups relationships into.
         * @enum {string}
         */
        RelationshipCategory: "structural" | "dependency" | "dynamic" | "other";
        /**
         * RelationshipCreate
         * @description A new link between two existing elements.
         */
        RelationshipCreate: {
            /** @description Only meaningful on an access relationship. */
            access_type?: components["schemas"]["AccessType"] | null;
            /**
             * Directed
             * @description Only meaningful on an association relationship.
             * @default false
             */
            directed?: boolean;
            /**
             * Name
             * @default
             */
            name?: string;
            /**
             * Properties
             * @description Free-form attributes, e.g. owner or criticality.
             */
            properties?: {
                [key: string]: string;
            };
            relationship_type: components["schemas"]["RelationshipType"];
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /**
             * Target Id
             * Format: uuid
             */
            target_id: string;
        };
        /**
         * RelationshipMatrixRead
         * @description One row of the 61x61 matrix of Appendix B, derived from the rules.
         *
         *     A row rather than the whole matrix: 3721 cells is a payload nobody reads,
         *     and a client always draws one source at a time.
         */
        RelationshipMatrixRead: {
            /** Rules */
            rules: components["schemas"]["RelationshipRuleRead"][];
            source: components["schemas"]["ElementType"];
        };
        /** RelationshipRead */
        RelationshipRead: {
            access_type: components["schemas"]["AccessType"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Directed */
            directed: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Properties */
            properties: {
                [key: string]: string;
            };
            relationship_type: components["schemas"]["RelationshipType"];
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            source_type: components["schemas"]["ElementType"];
            /**
             * Target Id
             * Format: uuid
             */
            target_id: string;
            target_type: components["schemas"]["ElementType"];
        };
        /**
         * RelationshipRuleRead
         * @description Which relationships one source type may open toward one target type.
         */
        RelationshipRuleRead: {
            /** Relationships */
            relationships: components["schemas"]["RelationshipType"][];
            target: components["schemas"]["ElementType"];
        };
        /**
         * RelationshipType
         * @description Every relationship type ArchiMate 3.2 defines.
         *
         *     Members are ordered from the strongest structural relationship to the
         *     weakest dependency, which is the order the specification uses when it
         *     derives an indirect relationship from a chain of direct ones.
         * @enum {string}
         */
        RelationshipType: "composition" | "aggregation" | "assignment" | "realization" | "serving" | "access" | "influence" | "association" | "triggering" | "flow" | "specialization";
        /**
         * RelationshipTypeRead
         * @description One relationship type, with what the metamodel says about using it.
         *
         *     `label` stays out on purpose: the display form is the client's business —
         *     the SPA writes these as French verbs — while the family, the strength and
         *     the direction of dependency are facts of ArchiMate the backend owns.
         */
        RelationshipTypeRead: {
            category: components["schemas"]["RelationshipCategory"];
            /**
             * Impact Follows Direction
             * @description Whether an outage at the source propagates along the arrow.
             */
            impact_follows_direction: boolean;
            /**
             * Strength
             * @description Higher binds tighter; a derived chain keeps the weakest.
             */
            strength: number;
            value: components["schemas"]["RelationshipType"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_document_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentRead"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revise_document_documents__document_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_revise_document_documents__document_id__put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentRead"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    discard_document_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_elements_elements_get: {
        parameters: {
            query?: {
                element_type?: components["schemas"]["ElementType"][] | null;
                layer?: components["schemas"]["Layer"][] | null;
                search?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ElementPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_element_elements_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ElementCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ElementRead"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_element_elements__element_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                element_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ElementRead"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_element_elements__element_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                element_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_element_elements__element_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                element_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ElementUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ElementRead"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_element_documents_elements__element_id__documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                element_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentSummaryRead"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attach_document_elements__element_id__documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                element_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_attach_document_elements__element_id__documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentRead"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_impact_elements__element_id__impact_get: {
        parameters: {
            query?: {
                depth?: number;
                relationship_type?: components["schemas"]["RelationshipType"][] | null;
            };
            header?: never;
            path: {
                element_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphRead"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_neighbourhood_elements__element_id__neighbourhood_get: {
        parameters: {
            query?: {
                depth?: number;
                relationship_type?: components["schemas"]["RelationshipType"][] | null;
            };
            header?: never;
            path: {
                element_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphRead"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_element_relations_elements__element_id__relationships_get: {
        parameters: {
            query?: {
                relationship_type?: components["schemas"]["RelationshipType"][] | null;
            };
            header?: never;
            path: {
                element_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphRead"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    read_metamodel_metamodel_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetamodelRead"];
                };
            };
        };
    };
    read_relationship_matrix_metamodel_matrix_get: {
        parameters: {
            query: {
                /** @description Type the links start at. */
                source: components["schemas"]["ElementType"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationshipMatrixRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_permitted_relationships_metamodel_relationships_get: {
        parameters: {
            query: {
                /** @description Type of the element the link starts at. */
                source: components["schemas"]["ElementType"];
                /** @description Type of the element the link ends at. */
                target: components["schemas"]["ElementType"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationshipType"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_relationships_relationships_get: {
        parameters: {
            query?: {
                element_id?: string | null;
                relationship_type?: components["schemas"]["RelationshipType"][] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationshipRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_relationship_relationships_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelationshipCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationshipRead"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_relationship_relationships__relationship_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                relationship_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
